version: "3"

services:
  # We recommend using a CockroachDB cluster for production deployments
  # For devnets and testnets postgres it's typically a better fit
  db:
    image: postgres:12
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive


  ingest:
    depends_on:
      - db
    restart: on-failure
    image: eldar/substrate-ingest:18
    environment:
      DATABASE_TYPE: postgres # set to  `cockroach` for CockroachDb
    command: [
       "-e", "wss://kusama-rpc.polkadot.io",
       "-e", "wss://kusama-rpc.polkadot.io",
       "-e", "wss://kusama-rpc.polkadot.io",
       "-e", "wss://kusama-rpc.dwellir.com",
       "-e", "wss://kusama-rpc.dwellir.com",
       "-e", "wss://kusama-rpc.dwellir.com",
       # add multiple endpoints to speed up the archiving.
       # adding the same endpoint will proprtionally increase the bandwidth and the indexing speed.
       #  "--start-block", "1000000", # comment out to specify a non-zero start block
       "--out", "postgres://postgres:postgres@db:5432/squid-archive"
    ]

  gateway:
    depends_on:
      - db
    image: tmcgroul/archive-gateway:32
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [
       "--database-url", "postgres://postgres:postgres@db:5432/squid-archive",
       # "--evm-support" # uncomment to additionally for a native support of Frontier EVM 
                         # (e.g. Moonbeam/Moonriver or Astar/Shiden)
    ]
    ports:
      - "8888:8000"

  # explorer service is optional, but provides a useful GraphQL interface for 
  # the on-chain data and rich filtering capabilities. 
  # It proved to be a indespensable tool for debugging, development and exploration
  explorer:
    image: tmcgroul/substrate-archive-openreader:1
    environment:
      DB_TYPE: postgres # set to `cockroach` for Cockroach DB
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "squid-archive"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      GRAPHQL_SERVER_PORT: "4350"
    ports:
      - "4350:4350"